# Generated by Django 5.2.6 on 2025-09-17 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_alter_subcategory_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(help_text="Short code, e.g., 'cj'", unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower number = higher priority"
                    ),
                ),
                ("credentials_json", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["priority", "code"],
            },
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Supplier's product/variant identifier",
                        max_length=255,
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original raw payload for traceability",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "provider_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_products",
                        to="providers.provideraccount",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_links",
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["variant"], name="providers_s_variant_7ea1c6_idx"
                    ),
                    models.Index(
                        fields=["provider_account"],
                        name="providers_s_provide_ca8dfb_idx",
                    ),
                    models.Index(
                        fields=["provider_account", "is_active"],
                        name="providers_s_provide_967a2c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_account", "external_id"),
                        name="uq_provider_external_id",
                    )
                ],
            },
        ),
    ]
