# Generated by Django 5.2.6 on 2025-09-18 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("error", "Error"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("first_error", models.TextField(blank=True, default="")),
                (
                    "provider_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="providers.provideraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["provider_account", "-started_at"],
                        name="providers_p_provide_d63af6_idx",
                    ),
                    models.Index(fields=["status"], name="providers_p_status_f73a70_idx"),
                ],
            },
        ),
    ]
