# Generated by Django 5.2.6 on 2025-09-16 19:20

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("brand", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="catalog_pro_slug_2b1eb6_idx"),
                    models.Index(fields=["is_active"], name="catalog_pro_is_acti_14fc6b_idx"),
                    models.Index(fields=["brand"], name="catalog_pro_brand_f6911e_idx"),
                    models.Index(fields=["category"], name="catalog_pro_categor_50f92a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(db_index=True, max_length=64, unique=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "price_base",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("NGN", "NGN"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                ("dims", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product_id", "sku"],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("doc", "Document"),
                            ("external", "External"),
                        ],
                        default="image",
                        max_length=16,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_set",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_set",
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty_available", models.PositiveIntegerField(default=0)),
                ("safety_stock", models.PositiveIntegerField(default=0)),
                ("warehouse", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "ordering": ["variant_id"],
            },
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(fields=["sku"], name="catalog_var_sku_93f218_idx"),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(fields=["is_active"], name="catalog_var_is_acti_aad294_idx"),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("product__isnull", False), ("variant__isnull", True)),
                    models.Q(("product__isnull", True), ("variant__isnull", False)),
                    _connector="OR",
                ),
                name="media_exactly_one_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("image__isnull", False),
                    models.Q(("url", ""), _negated=True),
                    _connector="OR",
                ),
                name="media_has_image_or_url",
            ),
        ),
    ]
