# Generated by Django 5.2.6 on 2025-09-17 04:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="media",
            name="media_exactly_one_fk",
        ),
        migrations.RemoveConstraint(
            model_name="media",
            name="media_has_image_or_url",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="alt_text",
            new_name="alt",
        ),
        migrations.RenameField(
            model_name="variant",
            old_name="weight_kg",
            new_name="weight",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="catalog_pro_categor_7c1c1f_idx",
            old_name="catalog_pro_categor_50f92a_idx",
        ),
        migrations.RemoveField(
            model_name="media",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="media",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="media",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="media",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="catalog/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "mov"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="catalog/images/"),
        ),
        migrations.AlterField(
            model_name="media",
            name="kind",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("external", "External URL"),
                ],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="catalog.variant",
            ),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(fields=["product", "sku"], name="catalog_var_product_852e8d_idx"),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True), ("variant__isnull", True)),
                fields=("product",),
                name="unique_main_media_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("variant",),
                name="unique_main_media_per_variant",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.subcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["subcategory"], name="catalog_pro_subcate_c7c91a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("category", "slug")},
        ),
    ]
