# Generated by Django 5.2.6 on 2025-09-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_category_subcategory_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("category", "name"), ("category", "slug")},
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(fields=["currency"], name="catalog_var_currenc_284ed4_idx"),
        ),
    ]
