# Generated by Django 5.2.6 on 2025-09-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_subcategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="home_rank",
            field=models.PositiveIntegerField(db_index=True, default=1000),
        ),
        migrations.AddField(
            model_name="product",
            name="is_handpicked",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_popular",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_recommended",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
